homeassistant:
  # Name of the location where Home Assistant is running
  name: HomeSysMoreno
  # Location required to calculate the time the sun rises and sets
  latitude: !secret home_latitude
  longitude: !secret home_longitude
  # Impacts weather/sunrise data (altitude above sea level in meters)
  elevation: !secret elevation
  # metric for Metric, imperial for Imperial
  unit_system: metric
  # Pick yours from here: http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
  time_zone: America/Sao_Paulo
  # Customization file
  customize: !include customize.yaml

# Show links to resources in log and frontend
#introduction:

# Enables the frontend
frontend:
  themes: !include_dir_merge_named themes/

# Enables configuration UI
config:

# Uncomment this if you are using SSL/TLS, running in Docker container, etc.
# http:
#   base_url: example.duckdns.org:8123

# Checks for available updates
# Note: This component will send some information about your system to
# the developers to assist with development of Home Assistant.
# For more information, please see:
# https://home-assistant.io/blog/2016/10/25/explaining-the-updater/
updater:
  # Optional, allows Home Assistant developers to focus on popular components.
  # include_used_components: true

# Discover some devices automatically
discovery:

# Allows you to issue voice commands from the frontend in enabled browsers
conversation:

# Enables support for tracking state changes over time
history:

# View all events in a logbook
logbook:

# Enables a map showing the location of tracked devices
map:

# Track the sun
sun:

# Text to speech
tts:
  - platform: google

# Cloud
cloud: !include cloud.yaml


#logger:
#        default: critical
#        logs:
#          homeassistant.components.switch: info


google:
  client_id: !secret calendar_id
  client_secret: !secret calendar_secret

group: !include groups.yaml
automation: !include automations.yaml
script: !include scripts.yaml
switch: !include switch.yaml
mqtt: !include mqtt.yaml
light: !include lights.yaml
device_tracker: !include device_tracker.yaml
notify: !include notify.yaml
media_player: !include media_players.yaml
shell_command: !include shell_commands.yaml
#camera: !include camera.yaml
sensor: !include sensors.yaml
zone: !include zone.yaml
weather: !include weater.yaml
input_select: !include input_select.yaml
input_number: !include input_number.yaml

http:
  base_url: !secret base_url        
  api_password: !secret api_password
